---
- hosts: jenkins-master
  become: true 
  tasks: 
  # Download the Jenkins key and save it to the specified location
  - name: download jenkins key
    get_url:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      dest: /usr/share/keyrings/jenkins-keyring.asc

  # Add the Jenkins repository to the apt sources list, using the downloaded key for verification
  - name: add jenkins repo 
    apt_repository: 
      repo: 'deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/'
      state: present 

  # Add the universe repository to ensure all necessary packages are available
  - name: add universe repository
    apt_repository:
      repo: 'deb http://archive.ubuntu.com/ubuntu/ focal universe'
      state: present

  # Update the apt package cache to ensure the latest package lists are used
  - name: update apt cache
    apt:
      update_cache: yes

  # Install Java (OpenJDK 17) to provide the necessary runtime environment for Jenkins
  - name: install java 
    apt: 
      name: openjdk-17-jre-headless
      state: present

  # Install Jenkins from the added repository
  - name: install jenkins 
    apt: 
      name: jenkins 
      state: present 

  # Start the Jenkins service to ensure it is running
  - name: start jenkins service 
    service: 
      name: jenkins 
      state: started 

  # Enable the Jenkins service to start automatically at boot time
  - name: enable jenkins to start at boot time 
    service: 
      name: jenkins 
      enabled: yes