---
- hosts: jenkins-master  # Target the jenkins-master group
  become: true  # Run as sudo

  tasks:

    - name: Update system packages  # Updates system repositories
      yum:
        name: '*'
        state: latest

    - name: Install required dependencies  # Installs dependencies needed for Jenkins
      yum:
        name:
          - java-11-amazon-corretto  # Amazon Linux supports Corretto (alternative to OpenJDK)
          - wget
        state: present

    - name: Add Jenkins repository  # Adds the official Jenkins repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins GPG key  # Adds the official GPG key for verification
      rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Install Jenkins  # Installs Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start and enable Jenkins service  # Ensures Jenkins runs on startup
      systemd:
        name: jenkins
        state: started
        enabled: yes
